### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by MisterOizo** [DragonicDefson/GOGUbisoft#1]
At least in June 2022 update on GOG, the Ubisoft Connect integration keeps getting "Connection lost":

![image](https://user-images.githubusercontent.com/28652233/174452062-4a7c25b4-b5cd-4047-a690-c76346f781ad.png)

When pressing Connect, there is another Connect to press:

![image](https://user-images.githubusercontent.com/28652233/174452160-d9a7476f-f14d-4434-b06a-e4fb20affee9.png)

For a brief time it flashes like below, and then returns to the first screenshot with Connection lost state.

![image](https://user-images.githubusercontent.com/28652233/174452092-feb23b4d-482b-48d3-8440-0696a0b268e5.png)

**Comment by DragonicDefson** [comment]
Just to point things down.

Have you replaced the original integration files with the ones in this repository?
Make sure to do so. I have another repository for the Bethesda integration, If you use Bethesda as well,
Bethesda deprecated their launcher which results in the integration being deprecated with it.
Make sure that you don't switched them out mistakenly.

Also, make sure that you have access to the Ubisoft API endpoints from your network.
I use the patched integration personally and running the GOG June 1 patch, and able to verify that it is working on my end.
Which can be seen on the screenshot below.

I will update the repository README file to include installation steps for easier replacement of the original integration.

![image](https://user-images.githubusercontent.com/37877161/174489247-93c5a7d7-783e-4740-a1e5-cf058e5527ad.png)


Have a nice day,
And if you have more questions regarding this issue,
Feel free to ask.

**Comment by MisterOizo** [comment]
> Just to point things down.
> 
> Have you replaced the original integration files with the ones in this repository? Make sure to do so. I have another repository for the Bethesda integration, If you use Bethesda as well, Bethesda deprecated their launcher which results in the integration being deprecated with it. Make sure that you don't switched them out mistakenly.
> 
> Also, make sure that you have access to the Ubisoft API endpoints from your network. I use the patched integration personally and running the GOG June 1 patch, and able to verify that it is working on my end. Which can be seen on the screenshot below.
> 
> I will update the repository README file to include installation steps for easier replacement of the original integration.
> 
> ![image](https://github.com/assets/37877161/93c5a7d7-783e-4740-a1e5-cf058e5527ad)
> 
> Have a nice day, And if you have more questions regarding this issue, Feel free to ask.

I did now and seems to work. Also in the instructions it's good to note that you should close GOG client while deleting/copying files. Thanks a lot and good day to you too!
